# Generated by Django 3.2.13 on 2022-05-28 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('model_image', models.ImageField(upload_to='images/')),
                ('proj_date', models.DateTimeField()),
                ('proj_body', models.TextField(max_length=500)),
            ],
        ),
    ]
